spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/txchallengedb
    username: txchallenge
    password: txchallenge
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
